"""first migrations

Revision ID: 056f1bdc02dd
Revises: 
Create Date: 2025-10-14 23:28:29.750252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056f1bdc02dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('filepath', sa.String(length=200), nullable=False),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
